### ISSUE TITLE
Define a deprecation policy for csi sidecars

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/docs#123]
It can mirror the Kubernetes policy.

Define policy on:
* sidecar CLI arguments
* sidecar behavior
* compatibility with K8s
* compatibility with CSI spec

This may also tie into defining our sidecar versioning scheme and what warrants a major, minor and patch version bump.

/assign
cc @jsafrane @pohly @saad-ali

**Comment by jsafrane** [comment]
+ RBAC policy changes (e.g. new leader election).

**Comment by pohly** [comment]
"CLI arguments", "RBAC policy" and "CSI spec" can all be considered as "compatibility with existing deployments": if a deployment swaps out the current version of a sidecar with a newer one, will the deployment still work?

"compatibility with K8S" is an extended version of that question: will the deployment still work *on the same clusters* as before?
