### ISSUE TITLE
Outdated and bad links for examples

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-csi/docs#124]
* [The example page](https://kubernetes-csi.github.io/docs/example.html) should be redone to point to new location of hostpath and hostpath doc https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/README.md.

* The link to Hostpath driver here is not working https://kubernetes-csi.github.io/docs/deploying.html

**Comment by pohly** [comment]
@okartau intents to work on that.

**Comment by pohly** [comment]
My suggestion is that most of the text in the example page gets replaced with a short description that kubernetes-csi uses the hostpath driver as example, then link to the csi-driver-host-path README.md for details.

That README.md then has to cover deploying the driver with the deploy script and then can copy most of the usage examples from the current example page.

**Comment by okartau** [comment]
liveness-probe is not covered by hostpath deployment, so this part remains documented here?

**Comment by okartau** [comment]
> and then can copy most of the usage examples from the current example page.

with "and then can copy" part you mean that we repeat examples from this page in hostpath, or we move them, or we link to them?

**Comment by msau42** [comment]
We should add liveness probe to hostpath so we can get e2e test coverage

**Comment by okartau** [comment]
I created a 1st draft PR, simply deleted duplicate part.
Here is some snapshotter material which is not on hostpath, to be migrated there?
Also, liveness-probe to be added (and doc migrated) on hostpath side, as was already mentioned here.

**Comment by pohly** [comment]
> with "and then can copy" part you mean that we repeat examples from this page in hostpath, or we move them, or we link to them?

I meant "move". There's no point in having duplicated content.
