### ISSUE TITLE
staging directory must be a pod volumeMount

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/docs#130]
If a CSI driver implements `NodeStageVolume`, then it must have a `volumeMount` entry which ensures that `/var/lib/kubelet/plugins/kubernetes.io/csi` (or is it `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/`?) is shared with the host.

Otherwise the driver is not going to see the staging directory that kubelet creates for it, like `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4863bcae-4b2f-11e9-9bd3-deadbeef0100/globalmount`.

In practice, drivers like gcepd have solved this instead by creating the staging directory themselves if needed:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/5d62c770f3e331e4236ebe42b74321f007f8c1e7/pkg/gce-pd-csi-driver/node.go#L201-L208

We should:
- document this special directory somewhere (https://kubernetes-csi.github.io/docs/deploying.html?)
- add it to the hostpath driver example deployment, even if it is not strictly needed there (no `NodeStageVolume`)

**Comment by msau42** [comment]
I wish it could have been a csi driver-specific directory instead of a generic csi directory (and drivers already have to import the driver-specific directory for the socket).  It makes it difficult to sort out which pv is from which csi driver.

But I think it needs to be a "csi" directory in order to support reconstruction, where we need a well known place to find the metadata file to figure out which driver it is in the first place.  @jsafrane can you confirm that is the reason?

**Comment by pohly** [comment]
Should the driver see the entire "csi" directory or is "csi/pv" enough? The less we expose the better, IMHO.

**Comment by jsafrane** [comment]
The staging directory probably can be csi-driver specific, however, it could be a breaking change between various kubelet versions - new kubelet should be able to unstage volumes staged by the old one + the same for downgrades.

IMO, reconstruction is not impacted, as it uses only `/var/lib/kubelet/pods/<uid>/*` and not staging directory.

> In practice, drivers like gcepd have solved this instead by creating the staging directory themselves if needed:

I am not sure I understand. The driver still needs to have VolumeMount with  `/var/lib/kubelet/plugins/kubernetes.io/csi` from the host and it still needs to have shared mount propagation there, otherwise the host won't see mounts there. IMO `MakeDir` in the driver code is just for robustness.

> Should the driver see the entire "csi" directory or is "csi/pv" enough? The less we expose the better, IMHO.

It's great if the driver sees as less as possible, but IMO the driver needs to have `/var/lib/kubelet/pods` anyway and it's able to see all data of all volumes, incl. secrets.

**Comment by pohly** [comment]
Jan Šafránek <notifications@github.com> writes:
>> In practice, drivers like gcepd have solved this instead by creating the staging directory themselves if needed:

Let me replace "solved" with "worked around" (unintentionally?).

> I am not sure I understand. The driver still needs to have VolumeMount
> with `/var/lib/kubelet/plugins/kubernetes.io/csi` from the host

It seems that it does not really need the hosts directly. In practice,
creating that directory locally inside the pod has worked fine.

> and it
> still needs to have shared mount propagation there, otherwise the host
> won't see mounts there.

That's not necessary. kubelet on the host must be completely oblivious
to what the CSI driver does with the staging directory. A driver can
mount on top of it or create something inside the directory and mount
there. Where mount propagation matters is for the actual target
directory.

In OIM, I have added a normal volume mount (no mount propagation) for
the staging directory. That works fine.

>> Should the driver see the entire "csi" directory or is "csi/pv" enough? The less we expose the better, IMHO.
>
> It's great if the driver sees as less as possible, but IMO the driver
> needs to have `/var/lib/kubelet/pods` anyway and it's able to see all
> data of all volumes, incl. secrets.

So it's already bad and "csi" vs. "csi/pv" won't matter much. I'd still
like to be as specific as possible.

**Comment by jsafrane** [comment]
>> The driver still needs to have VolumeMount
 with `/var/lib/kubelet/plugins/kubernetes.io/csi` from the host

> It seems that it does not really need the hosts directly. In practice,
creating that directory locally inside the pod has worked fine.
 
Interesting, I checked the code and indeed, `pv/` directory does not need to exist on the host at all, Kubernetes does not care.

> So it's already bad and "csi" vs. "csi/pv" won't matter much. I'd still like to be as specific as possible.

Ack, if we document it very carefuly. `pv/` now becomes part of our "API" and we can't change it.

**Comment by msau42** [comment]
> IMO, reconstruction is not impacted, as it uses only `/var/lib/kubelet/pods/<uid>/*` and not staging directory.

We store the volume metadata file in the staging directory.  So reconstruction needs to know how to get from the pod directory to the staging directory.

> creating that directory locally inside the pod has worked fine

If the driver restarts, then will those staging changes be lost?

**Comment by msau42** [comment]
> new kubelet should be able to unstage volumes staged by the old one + the same for downgrades.

We don't officially support node upgrade/downgrade without drain

**Comment by pohly** [comment]
> We store the volume metadata file in the staging directory. So reconstruction needs to know how to get from the pod directory to the staging directory.

Do you store it in `csi` or `csi/pv`? My understanding is that the CSI driver owns what's given to it entirely, i.e. it can do whatever it wants with `csi/pv`, like mounting something on top of it.

> If the driver restarts, then will those staging changes be lost?

I've not tried that.

**Comment by msau42** [comment]
Ok I was wrong about how reconstruction works.  There's save/load metadata file for mount device/unmountDevice.  And there's also save/load metadata during NewMounter/NewUnmounter.  And it's the file that's created by NewMounter that's used for reconstruction.

So I think it should be feasible to change the staging directory from the general CSI one to a driver-specific one

**Comment by pohly** [comment]
> So I think it should be feasible to change the staging directory from the general CSI one to a driver-specific one

But that is an API break, right? Kubernetes 1.13 and 1.14 already use `/var/lib/kubelet/plugins/kubernetes.io/csi`.
