### ISSUE TITLE
Add documentation on Snapshot secret support

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/docs#189]
The external-provisioner currently supports special key for specifying secret during volume provisioning. However, the https://kubernetes-csi.github.io/docs/secrets-and-credentials.html page does not document that.

So we should:

1. Add two sub pages to the "Secrets & Credentials" page, one for `external-provisioner` and one for `external-snapshotter` to document the "special keys" supported by both CSI volume and snapshot provisioning.
2. We should add use cases to the "Secrets & Credentials" page to document common use cases, for example:
    * For backend credential (which does not change per volume), just populate that directly in the CSI driver (does not need to go through CSI protocol.
    * For encrypting a disk or snapshot...

@oleksiys maybe a good candidate to help with 2.

**Comment by saad-ali** [comment]
CC @xing-yang @msau42

**Comment by saad-ali** [comment]
PR #190 addressed 1, but did not address 2 (documenting common use cases). Will leave this bug open to track that.

**Comment by saad-ali** [comment]
One more item: we should better document why SP should avoid deletion secrets (user could wipe out that secret), and suggest alternatives (for backend credentials, inject directly in to CSI driver; for storage pools, also inject directly in to CSI driver and select at runtime; etc.).

**Comment by xing-yang** [comment]
This is complete: https://kubernetes-csi.github.io/docs/secrets-and-credentials-volume-snapshot-class.html
