### ISSUE TITLE
Add topology and getting volume stats to the drivers feature table

### ISSUE THREAD

**Issue by wnxn** [kubernetes-csi/docs#214]
Kubernetes CSI supports topology and getting volume stats. 
We can add topology awareness and getting volume stats to the drivers feature table.

**Comment by msau42** [comment]
I think the drivers table is starting to get unwieldy with so many columns.  I am open to any suggestions on how to restructure the table to make it more condensed.  In the meantime though, I think topology and volume stats are not really optional features that users will be looking for when picking a CSI driver, so not worth explicitly documenting here.  Those two features I kind of consider as mandatory for a driver to function properly.

**Comment by j-griffith** [comment]
FYI I've opened https://github.com/kubernetes-csi/docs/issues/216 relating to this topic

**Comment by wnxn** [comment]
Thanks for @msau42 and @ggriffiths's consideration. I will keep track of #216 and close this issue.
