### ISSUE TITLE
Driver Feature table is a bit out of control

### ISSUE THREAD

**Issue by j-griffith** [kubernetes-csi/docs#216]
Keeping a table of [production plugins and the features they implement](https://github.com/kubernetes-csi/docs/blob/master/book/src/drivers.md#production-drivers) is handy, but as the project has grown, along with the number of plugins and features;  this simple table has become a bit difficult to view and even more difficult to update and keep accurate.

I don't have a solution to reformat what's in place, but I wonder if instead of trying to keep this up to date for features, replace the features columns with a link to the plugins documentation?  Said link could be a plugin doc (we could provide a template for plugin authors to use) and we could host that in this repo under sub-sections (sub-section for each plugin).

The downside of this is that users like to have the matrix in front of them to compare things, so this doesn't help with that.  It does however clean things up in terms of listing available plugins and their features; it provides the information, just no easy way to compare plugins.

Opening this issue to propose the template idea or to solicit input for a better suggestion if someone has one.

**Comment by msau42** [comment]
Removing the feature columns sound reasonable to me and leaving only the most important pieces. 

What do you think of keeping persistence and access mode columns and removing all the other subfeatures after?

**Comment by wnxn** [comment]
In my opinion, CSI driver features could split into two kinds, basic features and advanced features.
Basic features include creating/deleting volumes and mounting/unmounting volume on Pods.
Advanced features include expanding volume, snapshot management and other new features.

I think writing down features in one drivers table is very handy and intuitive. What do you think of integrating separated features columns in an advanced features column? Host feature table in this repo under sub-sections is a good idea to show various drivers.

We can keep Persistence, Access Mode and Dynamic Provisioning columns.

**Comment by msau42** [comment]
Do you mean something like this?

| Driver | Description | CSI Spec | Persistence | Access Mode | Provisioning | Other Features |
|-|-|-|-|-|-|-|
| foo | awesome driver | v1.0 | Persistent | RWO | Yes | Snapshots, Resizing, Cloning |
| bar | cool driver | v1.0 | Persistent | RWX | Yes | Resizing |

**Comment by wnxn** [comment]
> Do you mean something like this?
> 
> Driver	Description	CSI Spec	Persistence	Access Mode	Provisioning	Other Features
> foo	awesome driver	v1.0	Persistent	RWO	Yes	Snapshots, Resizing, Cloning
> bar	cool driver	v1.0	Persistent	RWX	Yes	Resizing

Yes.

**Comment by j-griffith** [comment]
@wnxn @msau42 I like that idea, md tables are still somewhat painful but the consolidation of columns makes it MUCH better IMO.  It also solves the annoying problem of adding a `?` mark to fill the space for unknowns.

**Comment by wnxn** [comment]
Hi, @j-griffith @msau42  
Can we name the column's head as `Other Features`?
What do you think of the options allowed to be filled are `Raw Block`, `Snapshot`, `Volume Expansion`, `Volume Cloning`, `Topology`, `Volume Stats` in `Other Features` ?  
I would like to submit a PR for this issue.

**Comment by msau42** [comment]
That sounds good to me. I'm still unsure about topology and volume stats because I feel like those are not quite optional features that a user would make a comparison on.
