### ISSUE TITLE
What is the difference between NodePublishVolume and NodeStageVolume？

### ISSUE THREAD

**Issue by wnxn** [kubernetes-csi/docs#24]
1. I would develope a CSI driver to make Kubernetes pod mount **block storage** provided by IaaS. 
Will I only implement six methods, such as  CreateVolume/DeleteVolume, ControllerPublish/ControllerUnpublish and NodePublishVolume/NodeUnpublishVolume?
2. I have a question about the difference between **NodePublishVolume** and **NodeStageVolume**.

**Comment by venkatsc** [comment]
Hey
I also had same doubt. After looking around for a while at the [csi internal plugin](https://github.com/kubernetes/kubernetes/blob/8b4cdd0f8593810c03693d0892ae922c9bea858b/pkg/volume/csi/csi_plugin.go) that is responsible for the above calls, it seems NodeStageVolume is an additional step for the block devices (see csi_block.go).

**Comment by wnxn** [comment]
Hi, after developing the [Qingcloud CSI plugin](https://github.com/yunify/qingcloud-csi) which passed the [CSI sanity test](https://github.com/kubernetes-csi/csi-test), I realize the meaning of those methods.
ControllerPublishVolume is used to attach disk to a node. NodeStageVolume is used to partition and format the disk and mount the disk on a node global directory. NodePublishVolume is used to bind mount the global directory on a container directory.
Finally, I recommend an article named *[How to write a Container Storage Interface (CSI) plugin](https://arslan.io/2018/06/21/how-to-write-a-container-storage-interface-csi-plugin/)*

**Comment by nvidhub** [comment]
@wnxn Excuse me，How do I get the implementation requirements of each csi function from the official？

**Comment by Wang-Kai** [comment]
> Hi, after developing the [Qingcloud CSI plugin](https://github.com/yunify/qingcloud-csi) which passed the [CSI sanity test](https://github.com/kubernetes-csi/csi-test), I realize the meaning of those methods. ControllerPublishVolume is used to attach disk to a node. NodeStageVolume is used to partition and format the disk and mount the disk on a node global directory. NodePublishVolume is used to bind mount the global directory on a container directory. Finally, I recommend an article named _[How to write a Container Storage Interface (CSI) plugin](https://arslan.io/2018/06/21/how-to-write-a-container-storage-interface-csi-plugin/)_

Thanks for your recommended article.
