### ISSUE TITLE
 Is this necessary to tell the user where to add the features?

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/docs#242]
![image](https://user-images.githubusercontent.com/13997135/70213752-1a6a2d80-1775-11ea-8ea8-6d352f7fe798.png)

For example: Only modify kube-apiserver, kube-controller or kubelet, or include all of them.

**Comment by msau42** [comment]
I would say we should keep things simple and expect that the feature gate needs to be set on all components

**Comment by zhucan** [comment]
@msau42 +1
