### ISSUE TITLE
Ambiguous terminology `Access Modes (RWO,ROX,RWX)`

### ISSUE THREAD

**Issue by hoyho** [kubernetes-csi/docs#246]
The table from 
https://github.com/kubernetes-csi/docs/blob/master/book/src/drivers.md#production-drivers
has column `Supported Access Modes` which has value like `Read/Write Single Pod` or  `Read/Write Multiple Pods`

According to Kubernetes document https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

>The access modes are:
> ReadWriteOnce – the volume can be mounted as read-write by a single node
> ReadOnlyMany – the volume can be mounted read-only by many nodes
> ReadWriteMany – the volume can be mounted as read-write by many nodes

My point is that Read/Write Multiple Pods is not equal to read-write by many nodes
case 1 : what if Pods in the same node？
case 2:  what if Pods in different node？

Also take a look at csi specification https://github.com/container-storage-interface/spec/blob/4731db0e0bc53238b93850f43ab05d9355df0fd9/csi.proto#L365
it also define AccessMode base on SINGLE_NODE/MULTI_NODE.

It is necessary to clarify **Access Mode**.

**Comment by saad-ali** [comment]
There is a long discussion about this issue here: https://groups.google.com/d/msg/container-storage-interface-community/-g_wma86P60/DlVw5_GIBQAJ

We should document the current mapping, in addition to figuring out how to make it better (in a backwards compatible way).

CC @bswartz

**Comment by bswartz** [comment]
I'm fairly confident there is no backwards compatible way to fix this. The least disruptive approach is to relax the CSI spec until it allows what Kubernetes already does, then to add new modes for users that really want the more restrictive behavior.
