### ISSUE TITLE
Best practices page

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/docs#269]
We should have a best practices page outlining suggestions for deploying CSI drivers that document things like:
* Tolerations on the DaemonSet
* Leader election
* Restricted RBACs

We can also extend that by providing a linter that vendors can use on their deployment specs. The linter could also detect things like:
* Outdated RBACs
* Deprecated options

@kubernetes-csi/csi-misc

**Comment by qaisarhayat12** [comment]
https://htwpk.blogspot.com/2020/04/dirilish-ertughral.html?m=1
