### ISSUE TITLE
Create a "Window Support" Section under "Features"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/docs#318]
[CSI Proxy Alpha](https://github.com/kubernetes-csi/csi-proxy) is complete. There are changes in Kubernetes 1.18 that enable its use.

We should add a new page under https://kubernetes-csi.github.io/docs/features.html for "Windows Support" to document CSI Windows Support (e.g. what do Kubernetes distributors need to do? what do CSI driver vendors need to do, etc.)

/assign @jingxu97 
CC @ddebroy @kkmsft @msau42

**Comment by msau42** [comment]
/remove-lifecycle stale

@jingxu97 @ddebroy what's the status on this?

**Comment by jingxu97** [comment]
the PR is https://github.com/kubernetes-csi/docs/pull/362

I will double check to address all the comments.

**Comment by msau42** [comment]
/remove-lifecycle rotten
@jingxu97 are we able to make progress on the documentation for this feature?

**Comment by jingxu97** [comment]
> /remove-lifecycle rotten
> @jingxu97 are we able to make progress on the documentation for this feature?

Yes, I am working on this part. Will send an update soon..

**Comment by msau42** [comment]
https://github.com/kubernetes-csi/docs/pull/362 is merged
/close
