### ISSUE TITLE
livenessprobe version info broken

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/docs#324]
The version table for https://kubernetes-csi.github.io/docs/livenessprobe.html currently looks like this:

Latest stable release | Branch | Min CSI Version | Max CSI Version | Container Image | Min K8s Version | Max K8s Version | --|--|--|--|--|-- livenessprobe v2.0.0 | release-2.0 | v1.0.0 | quay.io/k8scsi/livenessprobe:v2.0.0 | v1.13 | - livenessprobe v1.1.0 | release-1.1 | v1.0.0 | quay.io/k8scsi/livenessprobe:v1.1.0 | v1.13 | - Unsupported. | No 0.x branch. | v0.3.0 | quay.io/k8scsi/livenessprobe:v0.4.1 | v1.10 | v1.16

Looks like it may have broken in https://github.com/kubernetes-csi/docs/pull/290

CC @msau42

**Comment by pohly** [comment]
I was hoping that the mdlinter check that @humblec has proposed in https://github.com/kubernetes-csi/csi-release-tools/pull/83 would have caught this, but when I just tried it didn't.

It might still be worthwhile to consider integrating such a check.

**Comment by Madhu-1** [comment]
> I was hoping that the mdlinter check that @humblec has proposed in [kubernetes-csi/csi-release-tools#83](https://github.com/kubernetes-csi/csi-release-tools/pull/83) would have caught this, but when I just tried it didn't.
> 
> It might still be worthwhile to consider integrating such a check.

Yes the mdlinter won't check for the table format, its good to add `mdl` check for kubernetes-csi project. we can easily add YAML linter, shell check, and `mdl`

**Comment by humblec** [comment]
> I was hoping that the mdlinter check that @humblec has proposed in [kubernetes-csi/csi-release-tools#83](https://github.com/kubernetes-csi/csi-release-tools/pull/83) would have caught this, but when I just tried it didn't.
> 
> It might still be worthwhile to consider integrating such a check.
@pohly indeed, we should add more checks on the repo and I have followup PRs to add those , and I am on it.
