### ISSUE TITLE
Define support policy for major versions

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes-csi/docs#419]
Our support policy currently covers minor releases for one year, however it is not clear what is the support policy for older major versions.

Something we could do (for example) is:
> Every major release branch will be supported with minor releases for at least 1 year.

Or potentially:
> Only the most recent major release branch will be supported with minor releases.

This will have implications on how many cherry-picks we need to support once a feature makes it into master. Please feel free to note any other implications this support policy would have.

@msau42 @xing-yang

**Comment by msau42** [comment]
Some of my initial thoughts on this. Major versions are disruptive to consumers, so I do think we need to define some policy that balances the amount of upkeep we need to do maintain multiple major releases and the toil that gets imposed on consumers.

I'm thinking we can extend the "overlap" policy we have for minor releases to major releases as well:
```
In addition, the minor release branch will be supported for at least 3 months after the next minor version is released, to allow time to integrate with the latest release.
```

What this means is when we release a new major version, we also release a new minor version on the previous major.

**Comment by pohly** [comment]
> What this means is when we release a new major version, we also release a new minor version on the previous major.

What would be in that minor version release? This sentence sounds like we promise to do such a release regardless whether we have any relevant content for it or not.

**Comment by msau42** [comment]
My thoughts are there is some set of changes that caused us to bump the major version. The remaining changes, bug fixes and new features that don't depend on those breaking changes are candidates that can be included in the previous major release. If there are no such changes (ie, all changes were reasons to bump the major version), then we don't need to release anything on the previous major.

**Comment by xing-yang** [comment]
> What this means is when we release a new major version, we also release a new minor version on the previous major.

Are you suggesting we always release a new minor version at the time we release a new major version, or if the major version is released less than 3 months after the previous minor version release?  I don't think this should become a "regular" process.  This should be an exception.  We can define conditions that allow such an exception.

> The remaining changes, bug fixes and new features that don't depend on those breaking changes are candidates that can be included in the previous major release

I think this is too broad.  Bug fixes are fine, but we should define what kind of new features are qualified for minor release after a major release.  This issue came up because there is a request to backport metrics related feature.  So we can consider metrics as a type of feature that can qualify for a minor release in this case.

**Comment by jsafrane** [comment]
I think we should not backport features to older minor releases. We're adding them to the current minor release (unless they break the compatibility). Older minor branches should be only for bugfixes.

I agree with @msau42, we can extend the existing statement, I propose:
* The minor release branch (`2.y`) will be supported for at least 3 months after the next minor version is released (`2.y+1`).
* The newest old minor release branch (`2.y`) will be supported for at least 6 months after the next major version (`3.0`) is released.
* Whatever is longer "wins".

(IMO it's irrelevant if we release a new minor when a major is released - we may, we may not, it does not affect the support length with the rules above)

There's a catch though, major version may require new min. Kubernetes version. If the new major release requires say 1.25, we should support the old minor release branch while 1.24 is supported + some extra time (3 months?). I don't know how to put it into short and clear English though :-). My goal is to allow CSI driver vendors to have a single sidecar that works with all 3 supported Kubernetes versions + has a comfortable overlap to upgrade while the 4th Kubernetes version is out. Of course, such a sidecar may not use the latest Kubernetes features and it's IMO OK.

**Comment by msau42** [comment]
Discussed in CSI standup today:
- To minimize the number of branches we need to support, we will not have a general policy for releasing new minor versions on older majors. It will be exception-based instead.
    - In this particular case, the exception is to meet the PRR requirements that were enforced later
 - It's hard to limit major releases: often times bug fixes requires rbac changes
    - Can we make rbac changes an exception to not increase the major version? The changes still need to be clearly communicated.
 - Are there testing improvements we can do to actually test all our supported minor releases across all sidecars?
 - Any release process improvements?

**Comment by chrishenzie** [comment]
Discussed during Kubernetes CSI standup (1/24/22):
- The current expectation around minor version updates are that a deployment can be updated with the same command line flags and RBAC and it will work
- We probably shouldn't change that definition

Closing since this was the only remaining item for this issue.

/close
