### ISSUE TITLE
Update ChubaoFS references

### ISSUE THREAD

**Issue by tallclair** [kubernetes-csi/docs#493]
https://kubernetes-csi.github.io/docs/drivers.html?highlight=chubaofs#production-drivers leads to a github account that was taken over by a security researcher and reported to us through our HackerOne bounty program.

EDIT: 
ChubaoFS appears to have been renamed to cubeFS. The reference on the drivers page should be updated accordingly.

**Comment by tallclair** [comment]
The link was no longer pointing to the "account takeover" repo, so I assumed it was resolved. I just noticed that it's now essentially a redirect to "cubeFS" (https://github.com/cubefs/cubefs-csi). If that's desired, the link on the drivers index should probably be updated to that.

**Comment by Kartik494** [comment]
i would like to work on this.
