### ISSUE TITLE
broken link on container-storage-interface.md 

### ISSUE THREAD

**Issue by jmccormick2001** [kubernetes-csi/docs#526]
I see a broken link on https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#recommended-mechanism-for-deploying-csi-drivers-on-kubernetes

if someone can point me to the correct link, I'd be happy to create a PR to fix this.

**Comment by amolmote** [comment]
@jmccormick2001, I would like to work on this if you don't mind, I will look for solution.

**Comment by humblec** [comment]
@jmccormick2001 please check this https://kubernetes-csi.github.io/docs/deploying.html and replace accordingly .. please send a PR with the change ..

**Comment by jmccormick2001** [comment]
> @jmccormick2001, I would like to work on this if you don't mind, I will look for solution.

@amolmote sure, if you want to create the PR for this that is fine with me and thank you for offering!

**Comment by amolmote** [comment]
@jmccormick2001 please go ahead open the PR, you have found this issue.
/assign @jmccormick2001 
this is the solution
https://github.com/kubernetes/design-proposals-archive/blob/main/storage/container-storage-interface.md

**Comment by amolmote** [comment]
well done @jmccormick2001, actually i am not aware about this is your first pr in this organization because of this I wanted that you will open pr. thank you.
