### ISSUE TITLE
Update CSI driver docs for 1.27

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/docs#565]
Some sidecars are already released while others are in the progress of being released for 1.27. We need to update the CSI driver docs with the new sidecars.

https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.5.0
https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.3.0
https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.8.0
https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.8.0
https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.10.0

Also it would be great if we can have these tables to be automatically updated when the sidecars are released.

**Comment by coulof** [comment]
/assign @coulof

About the script, why not but... what is the support policy ? To keep three minor versions ? To keep everything less than a year old ?

For example, here is what I have for :
* node-driver-registrar : 
```
TITLE       TYPE         TAG NAME    PUBLISHED
v2.8.0      Latest       v2.8.0      about 3 days ago
v2.6.3                   v2.6.3      about 3 months ago
v2.7.0                   v2.7.0      about 4 months ago
v2.6.2                   v2.6.2      about 5 months ago
v2.6.1                   v2.6.1      about 5 months ago
v2.6.0                   v2.6.0      about 6 months ago
v2.5.1                   v2.5.1      about 11 months ago
v2.5.0                   v2.5.0      about 1 year ago
```
* external-provisioner
```        
TITLE   TYPE    TAG NAME  PUBLISHED
v3.5.0  Latest  v3.5.0    about 4 days ago
v3.4.1          v3.4.1    about 26 days ago
v3.3.1          v3.3.1    about 26 days ago
v3.2.2          v3.2.2    about 26 days ago
v3.4.0          v3.4.0    about 4 months ago
v3.3.0          v3.3.0    about 7 months ago
v3.2.1          v3.2.1    about 10 months ago
v3.1.1          v3.1.1    about 10 months ago
v3.2.0          v3.2.0    about 10 months ago
v3.1.0          v3.1.0    about 1 year ago
```
* external-attacher
```
TITLE           TYPE         TAG NAME    PUBLISHED
v4.3.0          Latest       v4.3.0      about 3 days ago
v4.2.0                       v4.2.0      about 2 months ago
v3.5.1                       v3.5.1      about 3 months ago
v4.1.0                       v4.1.0      about 4 months ago
v4.0.0                       v4.0.0      about 7 months ago
v3.5.0                       v3.5.0      about 10 months ago
v3.4.0                       v3.4.0      about 1 year ago
```

**Comment by coulof** [comment]
Here is a sample script : https://gist.github.com/coulof/fe25743763a59e080e3f01a4717f5dc9#file-get_supported_version_csi-sidecar-py-L42

It doesn't craft the entire table. To do so we must make sure of the meta-data on the releases page but... it is a good helper.

**Comment by xing-yang** [comment]
@coulof We've cut sidecar releases for 1.28. Can you help update the tables again?  Let me close this and open an issue for 1.28.
