### ISSUE TITLE
RBAC definitions

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/docs#62]
Depending on how the sidecar containers are deployed (for example, with or without leadership election), different RBAC definitions are needed. The example in this repo contain definitions that work for this particular example, but more documentation is needed.

The example also could be improved:
- granting permissions for endpoints in the `ClusterRole` is too broad, it should be limited to just endpoints in the driver's namespace via a `Role` (as in https://github.com/kubernetes/kubernetes/blob/60f736ed3d617f4770dc76657dd75a31bffb03f0/test/e2e/testing-manifests/storage-csi/controller-role.yaml)
- non-namespaced entities like ClusterRole should have unique names (like "csi-hostpath-attacher" instead of "csi-attacher") to avoid name collisions

Two options:
- each sidecar developer is responsible for documenting the required permissions as part of the individual releases and provides the reference .yaml filed, then the "doc" example links to these upstream definitions, *or*
- we choose this `docs` repo as the authoritative location for the deployment information of all sidecar containers

**Comment by msau42** [comment]
This should be addressed in each sidecar by now
/close
