### ISSUE TITLE
simplify deployments: avoid unnecessary env vars

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/docs#68]
Setting `--csi-address=$(CSI_ADDRESS)` is unnecessarily complex. The extra env variable isn't needed.

**Comment by msau42** [comment]
/remove-lifecycle stale

I think hostpath deployment still needs some cleanup

**Comment by pohly** [comment]
Another enhancement idea: remove stale sockets in a pre-stop lifecycle hook, similar to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/7295d5ee2dae0c48b7c23f476e5b224700ea1187/deploy/kubernetes/base/node.yaml#L23-L26

I think that can be done in the same PR, therefore I am mentioning it here. We might want to rename this issue to "enhance example deployment" then.
