### ISSUE TITLE
Add Makefile for docs

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/docs#78]
Updating docs is a two step process:

1. Update file in `book/*`
2. Run generation command to generate files in `docs/*`

We should add a Makefile at the root that makes it dead simple to run the command:

```
make all <-- generate all files
make clean <-- remove temp files
make clobber <-- remove all generated files
```

**Comment by leakingtapan** [comment]
I was originally proposing adding makefile for my `docker run --rm -v $(pwd):/data -u $(id -u):$(id -g) -it chengpan/mdbook:0.2.1 mdbook build ./book
` command to generate the book. Seems @lpabon had some concerns on owning the makefile. So this did happen. Not sure if he changed his opinion?
