### ISSUE TITLE
Outdated CSINodeInfo CRD URL

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-csi/docs#80]
The URL for CSINodeInfo is outdated here:
https://kubernetes-csi.github.io/docs/Setup.html#enabling-csinodeinfo

It was:
```
https://raw.githubusercontent.com/kubernetes/csi-api/master/pkg/crd/testdata/csinodeinfo.yaml
```

Not it becomes:
```
https://raw.githubusercontent.com/kubernetes/csi-api/master/pkg/crd/manifests/csinodeinfo.yaml
```

Also, the same issue for CSIDriver CRD

**Comment by pohly** [comment]
Should we limit the use of  URLs to the Example.md and just refer to it
under Setup.md?

If yes, then we only need to update URLs in one place.
If no, then Setup.md should also start using URLs with a revision
number.

**Comment by leakingtapan** [comment]
Or we can keep the URLs centralized in Setup.md and refer to it from Example.md. It makes more sense to me to put it under setup, since this is more driver setup related. But I don't have strong opinion on this.
